<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login</name>
   <tag></tag>
   <elementGuidId>4e483886-60aa-4299-a359-85db3c33e8b8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[normalize-space()='Login']
</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='orangehrm-login-forgot']</value>
      <webElementGuid>f3580190-ccfc-4f4b-8c01-80546e321b1b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
