<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>AccountVerification</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>9d05b9b4-790c-45b1-9d4d-196f56b26ab1</testSuiteGuid>
   <testCaseLink>
      <guid>8ab2c969-3439-4107-b423-f3a00c6487fb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SFDC/TC01_HFXLogIn</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b22ca989-f9b1-4fbf-a628-8f08fbff75f5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/SFDC/LogInData</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b22ca989-f9b1-4fbf-a628-8f08fbff75f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Url</value>
         <variableId>8e0ef832-23d5-4503-839a-26734d6d779e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b22ca989-f9b1-4fbf-a628-8f08fbff75f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Username</value>
         <variableId>017693f3-4423-4a8b-8a12-d4b40349b65c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b22ca989-f9b1-4fbf-a628-8f08fbff75f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Password</value>
         <variableId>0ef98a6c-0a70-4a5a-b7f8-3fb94ada16f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b50cb6d-3223-44c9-8a95-ca5b7777a173</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b22ca989-f9b1-4fbf-a628-8f08fbff75f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Environment</value>
         <variableId>de35254b-d2e6-4469-962f-7a75188406f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5d715815-431a-40f3-904c-6d44342ed630</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SFDC/TC02_AccountsNameSearch</testCaseId>
      <testDataLink>
         <combinationType>MANY</combinationType>
         <id>c5ace26a-008e-4fb5-a81d-77c2c75a9f8d</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-2</value>
         </iterationEntity>
         <testDataId>Data Files/SFDC/Profiles</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ea22572-3f4b-43f0-983f-89c86924739e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6febce38-fcca-47bc-afc3-e1dbfcb43f1c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>813b7265-d4af-4316-8472-33762d690f0c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4c702547-ebe2-4baf-a61d-624da1e10f00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c5ace26a-008e-4fb5-a81d-77c2c75a9f8d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Profile</value>
         <variableId>f319bdba-ea46-4466-b98c-19d0b577c539</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>56bea86b-1169-4259-b4bb-776b42f14a8a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SFDC/TC03_VerifyProfiles</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a913841f-ea07-4216-aa94-141a9c550c6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32129bbf-e62a-4252-93c1-540a0385f40a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f5cd1c5-e783-4225-b76d-7cc1133d45d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f43f989-fd95-49b4-80c6-9b9b7354e4e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0690f21-7d30-4ca9-8d44-1736ca3f4938</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8ed286e2-9d13-47a6-ba83-9e04d57c5ca7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d081f71-b93c-4b5b-9b71-1d98753b13f1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ceba5bc3-b2a2-4828-91bd-85956aade06e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SFDC/TC04_ChangeAccountName</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3e43a8d8-5e85-4d8b-b61a-06441ed7d4c5</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>2-5</value>
         </iterationEntity>
         <testDataId>Data Files/SFDC/Profiles</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63394cbd-8906-410f-8681-0f74dfee1d54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3e43a8d8-5e85-4d8b-b61a-06441ed7d4c5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Condition</value>
         <variableId>d862f87c-a2cd-4701-b586-c6fb1af883d1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3e43a8d8-5e85-4d8b-b61a-06441ed7d4c5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Profile</value>
         <variableId>b13c3bf6-1a43-40a0-badf-52437c2360c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c2e5dde8-469a-4318-9b8b-6ad6960a4f1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SFDC/TC05_ValidateMRMDetails</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3888a2ab-ef64-4a38-bc26-7426a15cc093</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c97dc052-9c14-4042-9ab6-4338d2c388d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SFDC/TC06_EditAccountDetails</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>38a920a1-f41b-471a-a256-e00a71fef062</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>4-5</value>
         </iterationEntity>
         <testDataId>Data Files/SFDC/Profiles</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3afecb6-e15e-4af2-a07d-2f24b31d2f11</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>828ff91e-82e0-4041-82ca-7e45befbe5f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>21d7353e-3ae5-4fab-8dc7-4233422b5d5a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>856e3cd5-6198-4664-bbd4-85b9e2e42ccf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1312fcdb-3661-4505-93c4-8df06384cfb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4bf585ff-7d16-4189-8d85-ac3aff0f73a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>38a920a1-f41b-471a-a256-e00a71fef062</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Profile</value>
         <variableId>8d5385ad-be00-45e4-8fa3-21e657d4715a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a9a21d9-2a13-4ced-9f99-a8f6df6b15af</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fb7d4976-eab0-43cf-8973-de5970c2ea23</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SFDC/TC07_VerifyChildAccount</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2792c75e-0a47-4388-9cb0-348506009a3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>350ac491-bf8e-4219-9e7b-b8c01c59c222</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b619dae5-186c-4974-8ca7-8afde67670cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>44b93350-3a46-4338-ae80-a39a375534cd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2afcefb-0231-424f-a1eb-a979d7113a96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a7fecc6-66d6-43e3-b036-451e0dc5de4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e59d99a0-7cb9-4da0-9810-e0cbcf8b09e1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a419526b-65ac-4015-8b68-2440009a5148</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>689655ef-a128-4beb-a123-344948656e04</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SFDC/TC08_UpdateScreeningStatus</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f583c52-567d-4b22-8794-6e2667fbc5e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6104362e-9c50-407d-bb3b-2191569da0f3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SFDC/TC09_VerifyingAccountPage</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>77529df9-a808-486d-a6c8-7b59987c9655</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>5</value>
         </iterationEntity>
         <testDataId>Data Files/SFDC/AllMessages</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7b4c0ab6-5343-48ef-8bc5-345b55754539</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d061e6c-d59d-4866-a9a2-257e052ae229</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd97f976-7cd5-42f3-967f-10ff57e42d4b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>77529df9-a808-486d-a6c8-7b59987c9655</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Message</value>
         <variableId>d69a7078-9c8d-45a7-9723-d11ce186a349</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e90e4667-49bd-45f9-a15f-646022bb8ee8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SFDC/TC10_CreateOpportunities</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>35cf04d4-c918-4a0c-ac80-36d18d85a567</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c57a7ac-5cdf-4e6a-b0e8-b19c26f706e6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b14e310-f256-4fff-a66f-fc66dfcb1368</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>764164dc-a4bd-4bad-8afd-daa900de570b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ae6a716-3083-468c-bd6a-f550b866b14f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>222f2be2-4fad-4427-a0d2-a523b0a1f224</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/SFDC/TC11_CreateAdditionalInfo</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3af3252-6f6f-4843-86ff-b7432e5cc728</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4eac928c-510d-44bd-b51f-bd501046353f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb62eff0-3019-4933-9899-7203c72486ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8250629-e71c-444c-85b2-10a48df5d096</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f6e7e90b-983d-4bc1-87ae-342589ff453e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2899164-9699-4ac5-a82a-1f3f3243b786</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf2edc2f-8060-4d8b-951c-3171c6d31d63</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bab592b2-38c6-47b1-bfa2-6ce05586514f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8247214e-b065-4b0c-80bb-66101a004663</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d6fefd6f-9052-45fa-a9fe-d1ef608c02b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/SFDC/TC12_EditOppotunityAndAccounts</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0b0b9f5-e891-41a9-8bcd-469a9bc35b3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60087941-1093-4f2b-a8e8-257c3634cada</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3b0d9084-aa77-4918-841e-249b2c8a6cf5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
